### ISSUE TITLE
Question regarding directory

### ISSUE THREAD

**Issue by dpassen** [psibi/justl.el#10]
From just's README:
```
just can be invoked from any subdirectory, not just the directory that contains the justfile.
```

so is there a way to make justl.el work from a subdirectory?

**Comment by psibi** [comment]
I should make the docs more clear, but this is the current state:

* The interactive function `justl-exec-recipe-in-dir` works from any sub directory. 
* The function `justl` works currently only from the directory where justfile is present.

**Comment by psibi** [comment]
Fixed via https://github.com/psibi/justl.el/pull/11
