### ISSUE TITLE
`justl--find-justfiles` fails on permissions

### ISSUE THREAD

**Issue by indigoviolet** [psibi/justl.el#12]
`.cache/dconf` happens to be owned by root, but this shouldn't affect `justl`

```
Debugger entered--Lisp error: (permission-denied "Opening directory" "Permission denied" "/home/venky/.cache/dconf")
  file-name-all-completions("" "/home/venky/.cache/dconf")
  directory-files-recursively("/home/venky/.cache/dconf" "justfile" nil nil nil)
  directory-files-recursively("/home/venky/.cache" "justfile" nil nil nil)
  directory-files-recursively("/home/venky/" "justfile")
  justl--find-any-justfiles("/home/venky/" "justfile")
  justl--find-justfiles("/home/venky/")
  justl--buffer-name()
  justl--save-line()
  justl()
  funcall-interactively(justl)
  command-execute(justl record)
  execute-extended-command(nil "justl" #("just" 0 4 (ws-butler-chg chg)))
  funcall-interactively(execute-extended-command nil "justl" #("just" 0 4 (ws-butler-chg chg)))
  command-execute(execute-extended-command)
```

**Comment by psibi** [comment]
Couple of questions/observations:

- Where exactly is your justfile present and from which directory are you invoking the *justl* command ?
- This mode tries to find the location of the justfile by traversing it's parent directory followed by traversing it's child directory (if it didn't find in the parent directories). My recommendation is to try executing the `justl` command from the directory where the justfile is present as a workaround.

**Comment by psibi** [comment]
After thinking a bit about this issue, `justl--find-justfiles` is central to how the entire mode works. So I'm closing this issue as won't fix.

But If you want to do some permissions checking or do any other workarounds, I'm open to a PR and we can iterate from there (or probably discuss the solution before we move to the PR stage).

I'm closing the issue, but let me know if you want to tackle this and I can open it. Thanks!

**Comment by indigoviolet** [comment]
Sorry for the late response:

My justfile is in $HOME, and I'm invoking `justl` from a (buffer for) a file in $HOME. Invoking from a subdirectory of $HOME works fine. The problem is that one of the child directories (`.cache/dconf`) is not readable by my user, and this breaks justl -- I don't see why this would be a core feature.

I think justl should just skip directories it can't access.

**Comment by psibi** [comment]
Can you try the latest commit ? I believe it might have gotten fixed in the
latest PR.
