### ISSUE TITLE
Only justfile filename is recognized

### ISSUE THREAD

**Issue by bram85** [psibi/justl.el#13]
`just` detects a justfile without regarding the case (so also accepts Justfile, JUSTFILE, etc.) and even .justfile if you want to hide it.

justl only recognizes 'justfile', so it would be nice if both tools perform the same lookup mechanism.

**Comment by psibi** [comment]
Yeah, I agree this is a issue.

> and even .justfile

I think this mode supports `.justfile` fine (Ref: https://github.com/psibi/justl.el/blob/73cb3a8f519dd555f73b981ac9c803b7489ce25b/justl.el#L189 ) That doesn't work for you ?

**Comment by bram85** [comment]
Yes, .justfile does work for me.

I wrote the issue with the 'just' README on one side and only seeing the hardcoded 'justfile' on the other side, assuming only 'justfile' is supported.

Then all is left is the case insensitive matching.

**Comment by psibi** [comment]
Cool, thanks for the confirmation. :-)

**Comment by psibi** [comment]
@bram85 Can you give this a try: https://github.com/psibi/justl.el/pull/14 ?

**Comment by bram85** [comment]
Yes seems to work ok, thank you.

**Comment by psibi** [comment]
Cool. Fixed via https://github.com/psibi/justl.el/pull/14

**Comment by liebkne** [comment]
Is the support for .justfile drop? The current code seems to find justfile only.

https://github.com/psibi/justl.el/blob/476bf9c4fc3d753589f1cf2c13dc4e1e14aaba7e/justl.el#L156

**Comment by psibi** [comment]
@liebkne Don't think that was intentional, PRs welcome.

**Comment by psibi** [comment]
Fixed via https://github.com/psibi/justl.el/pull/63
