### ISSUE TITLE
Major mode for *just* buffers could be compilation mode instead of fundamental mode

### ISSUE THREAD

**Issue by vmiheer** [psibi/justl.el#16]
This would allow to just use "g" to re-do that particular command and use other compilation mode shortcuts, including "C-c C-k" to kill the operation.

**Comment by psibi** [comment]
Yeah, this would be a nice thing to have.

**Comment by psibi** [comment]
I have implemented this as a separated derived mode on top of compilation mode here with tweaks specifically for justfile target execution: https://github.com/psibi/justl.el/pull/18

I'm closing this issue. Free feel to open new issues if you hit something up. Thanks!

**Comment by vmiheer** [comment]
Thank you!
