### ISSUE TITLE
Project & Projectile Hook

### ISSUE THREAD

**Issue by psionic-k** [psibi/justl.el#19]
When current file is in a project (or could be added to a project because it has VC root), there could be commands to dispatch just commands without opening the justfile.  Running should be more common (and supported) than writing for a tool like just.  While I can pop into vterm, it's extra steps.

**Comment by psibi** [comment]
We have the function `justl-exec-recipe-in-dir` for that. Can you see if that fits your use case ?

**Comment by psionic-k** [comment]
I studied the body of `justl-execute-recipe-in-dir` and believe it will work.

Comment needs fixup:
`;; M-x justl-execute-recipe-in-dir`

Recommend `justl-exec-recipe-at-point` for the in-buffer at-point function.  You can alias or deprecate without user harm.
https://github.com/psibi/justl.el/blob/master/justl.el#L637

You might want to re-order the documents.  Running has to be more common than reading. (and if reading was common, I would have found the function faster :clown_face: )

The directory traversal looks appropriate to find the justfile root without looking at the project state.  I haven't tried it yet inside justfile output buffers.  I'd be satisfied if this issue was closed as already addressed, but I'll leave that to you regarding the other nits

**Comment by psibi** [comment]
> Recommend justl-exec-recipe-at-point for the in-buffer at-point function. You can alias or deprecate without user harm.
https://github.com/psibi/justl.el/blob/master/justl.el#L637

Thanks for bringing it up, but I don't agree with that because the function would mean that it would take the just target from closest to point which is misleading in this case.

> You might want to re-order the documents. Running has to be more common than reading. (and if reading was common, I would have found the function faster clown_face )

Maybe, but the primary function of this mode is to run the target froms the list which is shown from the justl buffer. But I guess different people use it differently. :-)

>  I'd be satisfied if this issue was closed as already addressed, but I'll leave that to you regarding the other nits

Cool. :+1:
