### ISSUE TITLE
justl-exec-recipe-in-dir doesn't seem to use justl-compile-mode

### ISSUE THREAD

**Issue by treed** [psibi/justl.el#24]
I came here to ask for the justl-compile-mode feature and found that it had already been implemented, which is cool!

However, it seems not to work with justl-exec-recipe-in-dir. Perhaps I'm just missing something, but it would be nice to have justl-complie-mode work with both methods of interaction. :)

**Comment by psibi** [comment]
Yeah, good catch. It has been quite some time since I used `justl-exec-recipe-in-dir` as I have been using the `justl` way of interacting with it.

This should be relatively simple to fix, I will see if I can get to it soon.

**Comment by psibi** [comment]
Also, if you would want to send a PR, that's welcome too. :-)

**Comment by psibi** [comment]
@treed Can you see if this works for you: https://github.com/psibi/justl.el/pull/25 ?

**Comment by treed** [comment]
Yeah, this looks like it works, thanks!

I toyed around with it some but wasn't sure about what to pass for the directory. Glad to know I was on the right track at least.

**Comment by psibi** [comment]
Thanks for the confirmation!
