### ISSUE TITLE
justl-exec-recipe-in-dir should prompt for args when needed

### ISSUE THREAD

**Issue by MicahElliott** [psibi/justl.el#30]
According to README:

>Alternatively if you want to just execute a recipe quickly, call: `M-x justl-exec-recipe-in-dir`

But I don't see this working for recipes with args. The `completing-read` kindly prompts for which recipe to select, but then does not prompt for arg(s). So the outcome is like:

```
error: Recipe `browse-foo` got 0 arguments but takes 1
usage:
    just browse-foo SOMEARG
```

**Comment by psibi** [comment]
Thanks for the bug report! I have some functions to see if a recipe accepts arguments, so I believe this would be easy to fix.

Want to give an attempt at fixing this ?
