### ISSUE TITLE
Justl mostly broken over tramp

### ISSUE THREAD

**Issue by sochotnicky** [psibi/justl.el#31]
It seems that invoking justl commands over tramp connections fails. 

The only exception seems to be `justl-exec-recipe-in-dir` which I assume only works accidentally? 

Or are things supposed to work and there's problem on my end?

**Comment by sochotnicky** [comment]
I am still working on this as time permits but I have what seems to be mostly working version here:
https://github.com/sochotnicky/justl.el/tree/fix-tramp-support

There's still some weird bugs but I think those are unrelated to tramp and more related to how my justfiles are structured (aliases, arguments etc don't seem to be well supported).

Once I cleanup things a bit more I'll do a PR.

**Comment by psibi** [comment]
Nice! :-)

**Comment by psibi** [comment]
@sochotnicky Your version was helpful to me while adding support for tramp. Can you give this PR a try: https://github.com/psibi/justl.el/pull/36 ?

**Comment by psibi** [comment]
Fixed by https://github.com/psibi/justl.el/pull/36
