### ISSUE TITLE
Support optional arguments for justl-exec-recipe-in-dir

### ISSUE THREAD

**Issue by glucas** [psibi/justl.el#41]
When executing recipes from the justl buffer you have the option to "execute" or "execute with arguments". It would be great if there were a way to provide additional arguments when using `justl-exec-recipe-in-dir`. This could be an alternate command (like `justl-exec-recipe-in-dir-with-args`), but I was thinking you could handle an optional prefix argument. 

That way one could bind `justl-exec-recipe-in-dir` to e.g. `C-c j` and then use `C-u C-c j` when additional arguments are needed.

**Comment by glucas** [comment]
This seems similar to #30, which is closed but does not seem to work for me. I'm testing with a simple recipe like 

```
test target:
    echo '{{target}}'
```

and I don't get prompted for `target`. 

Initially I was thinking that #30 worked for required parameters but did not handle optional ones -- but neither is working for me.

**Comment by psibi** [comment]
I can reproduce the issue too with `justl-exec-recipe-in-dir`. I am open to receiving pull requests, although I am uncertain if I will have sufficient bandwidth to personally resolve it in near future.

**Comment by psibi** [comment]
Fixed via https://github.com/psibi/justl.el/pull/62
