### ISSUE TITLE
Create a buffer per command

### ISSUE THREAD

**Issue by TristanCacqueray** [psibi/justl.el#44]
Hello, would it be possible to add the command name to the `*just*` buffer so that we can run multiple long running commands in parallel?

For example, given a `ghcid` and `format` command, just.el would create one buffer per command:
- `*just-ghcid*`
- `*just-format*`

**Comment by psibi** [comment]
I see what you mean. This should be trivial to implement but I would prefer an optional opt-in via `defcustom` as I don't want to populate emacs instance with lots of different just buffers. I would be happy to accept a PR for the same.

**Comment by TristanCacqueray** [comment]
@Munksgaard My emacs-fu is also weak, but perhaps this should work (as it is done in the test):

```elisp
(lambda () (progn
  (customize-set-variable 'justl-per-recipe-buffer 't)
  (justl-exec-recipe-in-dir)
  (customize-set-variable 'justl-per-recipe-buffer nil)))
```

**Comment by Munksgaard** [comment]
Cool, that seems to work!

> (define-key justl-mode-map (kbd "n") 'justl-exec-new-buffer)

This is surprised me a bit, as `n` is commonly used to navigate up and down in the buffer, right? 

Anyway, thanks for the response :)

**Comment by Munksgaard** [comment]
Hm, it only works with justl-exec-recipe. Is it possible to get it to work with justl-exec-recipe-in-dir? Specifically, I'm looking to do something like:

```elisp
(define-key project-prefix-map "J" 'justl-exec-recipe-in-dir-new-buffer)
```
