### ISSUE TITLE
Support positional arguments?

### ISSUE THREAD

**Issue by gamb** [psibi/justl.el#50]
As far as I can tell I can't run scripts with positional arguments (`$1` etc.) yet?

**Comment by psibi** [comment]
Yeah, it would be nice to have this. I would be happy to accept a PR for the same.

**Comment by gamb** [comment]
Great :) Will take a look if I find a bit of time on the weekend

**Comment by psibi** [comment]
Does using `w` key binding to pass the positional argument work for you ?

**Comment by gamb** [comment]
> Does using `w` key binding to pass the positional argument work for you ?

Sounds good to me!

**Comment by psibi** [comment]
Cool, closing the issue then as you can use that to pass positional arguments.
