### ISSUE TITLE
Feature request - option to prevent selecting the justl buffer when running

### ISSUE THREAD

**Issue by bbbscarter** [psibi/justl.el#67]
At the moment when you run a justl command, input focus shifts to the justl buffer. Depending on what you're doing this isn't always what you want - e.g. in the case of using justl to issue compilation commands, you might want it to behave like a standard compilation buffer.

Having an option to toggle this behaviour would be useful.

PR incoming!

**Comment by psibi** [comment]
Fixed by https://github.com/psibi/justl.el/pull/68
