### ISSUE TITLE
justl doesn't work when justl-pop-to-buffer-on-display is nil

### ISSUE THREAD

**Issue by psibi** [psibi/justl.el#72]
Reproducible with this configuration:

```
(use-package justl
  :ensure t
  :custom
  (justl-recipe-width 40)
  (justl-pop-to-buffer-on-display nil)
  (justl-include-private-recipes nil))
```

Steps to reproduce:
- Go to a specific justfile
- M-x justl
- You see a new buffer opened but it's blank. Surprisingly if I close that buffer, the actual justfile has been replaced with the contents that I would expect in the justl buffer.

CC: @bbbscarter

**Comment by bbbscarter** [comment]
I've put up  request to fix this.

Apologies! I've only used 'justl-exec-*' commands, which don't exhibit this behaviour. The fix is simple, as described in the CL.
